# Generated by Django 5.2 on 2025-06-01 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'rol__codigo': 'DOC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.perfil'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='modalidad',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'En línea')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('INSCRITO', 'Inscrito'), ('APROBADO', 'Aprobado'), ('REPROBADO', 'Reprobado'), ('RETIRADO', 'Retirado')], default='INSCRITO', max_length=20),
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.inscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='SesionAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('presente', models.BooleanField(default=False)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.inscripcion')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
