# Generated by Django 5.2 on 2025-06-01 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_inscripcion_usuario_curso_docente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='solicitud_baja',
            field=models.CharField(choices=[('NINGUNA', 'Ninguna'), ('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='NINGUNA', max_length=10),
        ),
        migrations.AlterField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__codigo': 'DOC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.perfil'),
        ),
    ]
