# Generated by Django 5.0.3 on 2025-06-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_membresia'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='valido_para_membresia',
            field=models.BooleanField(default=False),
        ),
    ]
