# Generated by Django 5.0.3 on 2025-06-02 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_curso_valido_para_membresia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('limite_precio_curso', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='valido_para_membresia',
        ),
        migrations.AddField(
            model_name='perfil',
            name='plan_membresia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.planmembresia'),
        ),
        migrations.DeleteModel(
            name='Membresia',
        ),
    ]
