# Generated by Django 5.0.3 on 2025-06-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_planmembresia_remove_curso_valido_para_membresia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fecha_fin_membresia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_inicio_membresia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
